name: AWS Lambda

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment:
      name: aws-lambda

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActions

    - name: get-caller-identity is allowed to run on role.
      run: aws sts get-caller-identity

    - name: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Create deploy_package
      run: |
        cd backend/hello_world
        python -m pip install -r ./requirements.txt --target .
        zip deploy_package.zip . -r -x Pipfile Pipfile.lock requirements.txt

    - name: Print deploy_package.zip file size
      run: |
        cd backend/hello_world
        ls -lh | grep deploy_package.zip

    - name: lambda update
      run: |
        cd backend/hello_world
        python -m pip install awscli
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://deploy_package.zip \
          --publish
