# 参考: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-vue-and-nuxt
name: GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Get yarn cache
      id: yarn-cache
      run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> "${GITHUB_OUTPUT}"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache.outputs.YARN_CACHE_DIR }}
        key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-website-

    # yarn.lock を生成せず、更新がある場合に落ちます。
    - run: |
        cd frontend
        yarn install --frozen-lockfile
        VUE_APP_BACKEND_BASE_URL=${{ secrets.VUE_APP_BACKEND_BASE_URL }} yarn build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        # Note that the GITHUB_TOKEN is NOT a personal access token.
        # A GitHub Actions runner automatically creates a GITHUB_TOKEN secret to authenticate in your workflow.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
